### ISSUE TITLE
Just don't

### ISSUE THREAD

**Issue by emeruvia** [ChristianBedwell/Xamarin-Android-Practice#1]
Honestly, I wouldn't spend too much time (if any) learning Xamarin for Android development. Instead, I would look into React Native, Flutter or even Ionic. Those languages are more versatile and have a bigger market than Xamarin.
Flutter: https://flutter.dev
React Native: https://facebook.github.io/react-native/
Ionic: https://ionicframework.com/

**Comment by ChristianBedwell** [comment]
@emeruvia Thanks for the information, I didn't know of Xamarin's unpopularity in mobile app development, the reason I recently started with Xamarin tutorials is because a few of the local companies in the Southwest Florida area use the Xamarin framework. I actually practiced a little React Native not too long ago, but I haven't yet worked with Flutter or Ionic.

**Comment by emeruvia** [comment]
The beauty of mobile app development is that on its core, it's almost all the same. The main reason why I would advise to stay off from Xamarin is that it's a dying market. With the growth of react native and most recently Flutter, the development in Xamarin is slowly going to stop.
Personally, I would try to look into Ionic or React Native, since if you can't find a job on the mobile development area, you might be able to find something in their web counterparts (Angular and React). 
I'm not saying to stop doing Xamarin and focus solely on other popular frameworks. Just don't invest too much time trying to figure out everything about mobile development in Xamarin. I suggest just jump into it and make a small project, similar to something you've done in Native app development, and see how it goes.
